SELECT D.NAME   AS `Department`,
       E.NAME   AS `Employee`,
       E.SALARY AS `Salary`
FROM EMPLOYEE E
         JOIN (SELECT DEPARTMENTID, MAX(SALARY) AS MAXSALARY
               FROM EMPLOYEE
               GROUP BY DEPARTMENTID) AS M
         JOIN DEPARTMENT D
WHERE E.DEPARTMENTID = M.DEPARTMENTID
  AND E.DEPARTMENTID = D.ID
  AND E.SALARY = M.MAXSALARY