-- 273709
select sum(price) as `TOTAL_PRICE`
from item_info
where rarity = 'LEGEND';

-- 131115
select *
from FOOD_PRODUCT
where PRICE = (select max(price) from FOOD_PRODUCT);

-- 298515
select concat(max(length), "cm") as `MAX_LENGTH`
from fish_info;

-- 131697
SELECT max(PRICE) as `MAX_PRICE`
from PRODUCT;

-- 157339
SELECT car.CAR_ID,
       car.CAR_TYPE,
       TRUNCATE(
               car.DAILY_FEE * 30 * (100 - IFNULL(dp.DISCOUNT_RATE, 0)) / 100,
               0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS car
         LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS hist
                   ON hist.CAR_ID = car.CAR_ID
                       AND hist.START_DATE <= '2022-11-30'
                       AND hist.END_DATE >= '2022-11-01'
         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS dp
              ON dp.CAR_TYPE = car.CAR_TYPE
                  AND dp.DURATION_TYPE = '30일 이상'
WHERE hist.CAR_ID IS NULL
  AND car.CAR_TYPE IN ('세단', 'SUV')
  AND TRUNCATE(
              car.DAILY_FEE * 30 * (100 - IFNULL(dp.DISCOUNT_RATE, 0)) / 100,
              0) <= 2000000
GROUP BY car.CAR_ID
ORDER BY FEE DESC, car.CAR_ID DESC;

-- 273711
SELECT DISTINCT child.ITEM_ID,
                child.ITEM_NAME,
                child.RARITY
FROM ITEM_TREE it
         JOIN ITEM_INFO parent
              ON parent.ITEM_ID = it.PARENT_ITEM_ID
                  AND parent.RARITY = 'RARE'
         JOIN ITEM_INFO child
              ON child.ITEM_ID = it.ITEM_ID
ORDER BY child.ITEM_ID DESC;

-- 299307
SELECT ID,
       CASE
           WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
           WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
           WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH'
           END
           AS `SIZE`
FROM ECOLI_DATA
ORDER BY ID;

-- 299305
SELECT p.ID,
       COUNT(c.ID) AS CHILD_COUNT
FROM ECOLI_DATA p
         LEFT JOIN ECOLI_DATA c
                   ON c.PARENT_ID = p.ID
GROUP BY p.ID
ORDER BY p.ID;

-- 301647
SELECT child.ID, child.GENOTYPE, parent.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA child
         JOIN ECOLI_DATA parent
              ON parent.ID = child.PARENT_ID
WHERE parent.GENOTYPE | child.GENOTYPE = child.GENOTYPE
ORDER BY child.ID;

-- 301649
SELECT ID,
       CASE
           WHEN RATE <= 0.25 THEN 'LOW'
           WHEN RATE <= 0.50 THEN 'MEDIUM'
           WHEN RATE <= 0.75 THEN 'HIGH'
           ELSE 'CRITICAL'
           END AS COLONY_NAME
FROM (SELECT ID,
             PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS RATE
      FROM ECOLI_DATA) t
ORDER BY ID;

-- 361650
WITH RECURSIVE GEN(ID, PARENT_ID, LEVEL) AS (SELECT ID, PARENT_ID, 1 AS LEVEL
                                             FROM ECOLI_DATA
                                             WHERE PARENT_ID IS NULL
                                             UNION ALL
                                             SELECT N.ID, N.PARENT_ID, GEN.LEVEL + 1
                                             FROM ECOLI_DATA N
                                                      JOIN GEN ON N.PARENT_ID = GEN.ID
                                             WHERE LEVEL < 3)
SELECT ID
FROM GEN
WHERE LEVEL = 3
ORDER BY ID;

-- 131532
SELECT YEAR(OS.SALES_DATE)        AS YEAR,
       MONTH(OS.SALES_DATE)       AS MONTH,
       UI.GENDER                  AS GENDER,
       COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE OS
         JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER;

-- 301651
WITH RECURSIVE GEN(ID, PARENT_ID, LEVEL) AS (SELECT ID, PARENT_ID, 1
                                             FROM ECOLI_DATA
                                             WHERE PARENT_ID IS NULL
                                             UNION ALL
                                             SELECT EC.ID, EC.PARENT_ID, GEN.LEVEL + 1
                                             FROM ECOLI_DATA EC
                                                      JOIN GEN ON GEN.ID = EC.PARENT_ID)

SELECT COUNT(DISTINCT E.ID) AS `COUNT`,
       GEN.LEVEL            AS `GENERATION`
FROM ECOLI_DATA E
         JOIN GEN
              ON GEN.ID = E.ID
         LEFT JOIN ECOLI_DATA E2
                   ON E2.PARENT_ID = E.ID
WHERE E2.ID IS NULL
GROUP BY GEN.LEVEL
ORDER BY GEN.LEVEL
;

-- 276013
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS
WHERE SKILL_1 = 'Python'
   OR SKILL_2 = 'Python'
   OR SKILL_3 = 'Python'
ORDER BY ID;

-- 276034
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
         JOIN SKILLCODES S
              ON S.NAME IN ('Python', 'C#') AND D.SKILL_CODE | S.CODE = D.SKILL_CODE
ORDER BY D.ID;

-- 293258
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE LENGTH IS NULL;

-- 298517
SELECT FI.ID, FI.LENGTH
FROM FISH_INFO FI
ORDER BY FI.LENGTH DESC, FI.ID ASC
LIMIT 10;

-- 298518
SELECT COUNT(*) AS `FISH_COUNT`
FROM FISH_INFO FI
         JOIN FISH_NAME_INFO FNI
              ON FNI.FISH_TYPE = FI.FISH_TYPE
WHERE FNI.FISH_NAME IN ('BASS', 'SNAPPER');

-- 157340
SELECT c.CAR_ID,
       CASE
           WHEN EXISTS (SELECT 1
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
                        WHERE h.CAR_ID = c.CAR_ID
                          AND '2022-10-16' BETWEEN h.START_DATE AND h.END_DATE)
               THEN '대여중'
           ELSE '대여 가능'
           END AS AVAILABILITY
FROM (SELECT DISTINCT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) c
ORDER BY c.CAR_ID DESC;

-- 131124
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR
         JOIN (SELECT MEMBER_ID
               FROM REST_REVIEW
               GROUP BY MEMBER_ID
               ORDER BY COUNT(MEMBER_ID) DESC
               LIMIT 1) FILTER ON FILTER.MEMBER_ID = RR.MEMBER_ID
         JOIN MEMBER_PROFILE MP
              ON MP.MEMBER_ID = RR.MEMBER_ID
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_DATE ASC;

-- 144856
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES BS
         JOIN BOOK B
              ON B.BOOK_ID = BS.BOOK_ID
         JOIN AUTHOR A
              ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(BS.SALES_DATE) = 2022
  AND MONTH(BS.SALES_DATE) = 1
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;

-- 299310
SELECT YEAR(E.DIFFERENTIATION_DATE) AS `YEAR`, FILTER.LARGEST - SIZE_OF_COLONY AS `YEAR_DEV`, E.ID AS `ID`
FROM ECOLI_DATA E
         JOIN (SELECT MAX(SIZE_OF_COLONY) AS LARGEST, YEAR(DIFFERENTIATION_DATE) AS YEAR
               FROM ECOLI_DATA
               GROUP BY YEAR(DIFFERENTIATION_DATE)) FILTER ON FILTER.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR(E.DIFFERENTIATION_DATE) ASC, `YEAR_DEV` ASC;

-- 131116
SELECT FP.CATEGORY, SUB.PRICE AS `MAX_PRICE`, FP.PRODUCT_NAME AS `PRODUCT_NAME`
FROM FOOD_PRODUCT FP
         JOIN (SELECT MAX(PRICE) AS PRICE, CATEGORY
               FROM FOOD_PRODUCT
               GROUP BY CATEGORY) AS SUB ON SUB.CATEGORY = FP.CATEGORY
WHERE SUB.PRICE = FP.PRICE
  AND FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY SUB.PRICE DESC;

-- 59413
WITH RECURSIVE T AS (SELECT 0 AS HOUR
                     UNION ALL
                     SELECT T.HOUR + 1
                     FROM T
                     WHERE HOUR < 23)

SELECT T.HOUR AS HOUR, COUNT(DISTINCT AO.ANIMAL_ID) AS COUNT
FROM T
         LEFT JOIN ANIMAL_OUTS AO
                   ON HOUR(AO.DATETIME) = T.HOUR
GROUP BY T.HOUR
ORDER BY T.HOUR

-- 276036
SELECT CASE
           WHEN SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
               AND SUM(CASE WHEN S.NAME = 'Python' THEN 1 ELSE 0 END) > 0
               THEN 'A'
           WHEN SUM(CASE WHEN S.NAME = 'C#' THEN 1 ELSE 0 END) > 0
               THEN 'B'
           WHEN SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) > 0
               THEN 'C'
           END AS GRADE,
       D.ID    AS ID,
       D.EMAIL AS EMAIL
FROM DEVELOPERS D
         JOIN SKILLCODES S
              ON S.CODE & D.SKILL_CODE != 0
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, D.ID;


-- 131534
WITH C AS (SELECT COUNT(USER_ID) AS USER_COUNT
           FROM USER_INFO
           WHERE YEAR(JOINED) = '2021'),

     J AS (SELECT USER_ID
           FROM USER_INFO
           WHERE YEAR(JOINED) = '2021')

SELECT YEAR(SALES_DATE)                                   AS YEAR,
       MONTH(SALES_DATE)                                  AS MONTH,
       COUNT(DISTINCT J.USER_ID)                          AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT J.USER_ID) / C.USER_COUNT, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
         JOIN J
              ON J.USER_ID = OS.USER_ID
         CROSS JOIN C
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE);

-- 276035
SELECT D.ID,
       D.EMAIL,
       D.FIRST_NAME,
       D.LAST_NAME
FROM DEVELOPERS D
         JOIN SKILLCODES S
              ON S.CODE & D.SKILL_CODE != 0
WHERE S.CATEGORY = 'Front End'
GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY D.ID;

-- 284529
SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, ROUND(AVG(HE.SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES HE
         JOIN HR_DEPARTMENT HD
              ON HD.DEPT_ID = HE.DEPT_ID
GROUP BY HD.DEPT_ID, HD.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;

-- 284528
SELECT HE.EMP_NO,
       HE.EMP_NAME,
       CASE
           WHEN HG.SCORE >= 96 THEN 'S'
           WHEN HG.SCORE >= 90 THEN 'A'
           WHEN HG.SCORE >= 80 THEN 'B'
           ELSE 'C'
           END
           AS GRADE,
       CASE
           WHEN HG.SCORE >= 96 THEN HE.SAL * 0.2
           WHEN HG.SCORE >= 90 THEN HE.SAL * 0.15
           WHEN HG.SCORE >= 80 THEN HE.SAL * 0.1
           ELSE 0
           END
           AS BONUS
FROM HR_EMPLOYEES HE
         JOIN (SELECT EMP_NO, YEAR, AVG(SCORE) AS SCORE
               FROM HR_GRADE
               GROUP BY EMP_NO, YEAR) HG
              ON HG.EMP_NO = HE.EMP_NO
ORDER BY HE.EMP_NO;

-- 133026
SELECT II.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF FH
         JOIN ICECREAM_INFO II
              ON II.FLAVOR = FH.FLAVOR
GROUP BY II.INGREDIENT_TYPE;

-- 131123
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
         JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
               FROM REST_INFO
               GROUP BY FOOD_TYPE) AS SUB ON SUB.FOOD_TYPE = RI.FOOD_TYPE AND SUB.FAVORITES = RI.FAVORITES
ORDER BY RI.FOOD_TYPE DESC;

-- 151137
SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%'
   OR OPTIONS LIKE '%열선시트%'
   OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE;

-- 132202
SELECT MCDP_CD AS `진료과코드`, COUNT(*) AS `5월예약건수`
FROM APPOINTMENT
WHERE YEAR(APNT_YMD) = 2022
  AND MONTH(APNT_YMD) = 5
GROUP BY MCDP_CD
ORDER BY `5월예약건수` ASC, `진료과코드` ASC;

-- 164668
SELECT U.USER_ID, U.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
         JOIN USED_GOODS_USER U
              ON U.USER_ID = UGB.WRITER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;

-- 144855
SELECT CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
         JOIN BOOK B
              ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = 2022
  AND MONTH(BS.SALES_DATE) = 1
GROUP BY CATEGORY
ORDER BY CATEGORY;

-- 131530
SELECT TRUNCATE(PRICE, -4) as PRICE_GROUP,
       COUNT(*)            as PRODUCTS
FROM PRODUCT
GROUP BY TRUNCATE(PRICE, -4)
ORDER BY 1;

-- 284527
SELECT HG.SCORE,
       HE.EMP_NO,
       HE.EMP_NAME,
       HE.POSITION,
       HE.EMAIL
FROM HR_EMPLOYEES HE
         JOIN (SELECT SUM(SCORE) AS SCORE, EMP_NO
               FROM HR_GRADE
               GROUP BY EMP_NO) HG ON HG.EMP_NO = HE.EMP_NO
ORDER BY HG.SCORE DESC
LIMIT 1;

-- 284531
SELECT ROUTE,
       CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), "km") AS TOTAL_DISTANCE,
       CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), "km") AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY TOTAL_DISTANCE DESC;

-- 284531
SELECT ROUTE,
       CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), "km") AS TOTAL_DISTANCE,
       CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), "km") AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 2) DESC;

-- 293257
SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
FROM FISH_INFO
         JOIN FISH_NAME_INFO
              ON FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
GROUP BY FISH_NAME_INFO.FISH_TYPE, FISH_NAME
ORDER BY FISH_COUNT DESC;

-- 293260
SELECT COUNT(*) AS FISH_COUNT, MONTH(TIME) AS MONTH
FROM FISH_INFO
GROUP BY MONTH(TIME)
ORDER BY MONTH;

-- 273712
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC;

-- IS NULL
-- 273710
SELECT IT.ITEM_ID, IT.ITEM_NAME
FROM ITEM_INFO IT
         JOIN ITEM_TREE ITT
              ON ITT.ITEM_ID = IT.ITEM_ID
WHERE ITT.PARENT_ITEM_ID IS NULL
ORDER BY IT.ITEM_ID;

-- 131114
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%';

-- 131528
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE AGE IS NULL;

-- 293259
SELECT ROUND(AVG(COALESCE(LENGTH, 10)), 2) AS AVERAGE_LENGTH
FROM FISH_INFO;

-- 157341
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
              ON H.CAR_ID = C.CAR_ID
WHERE MONTH(H.START_DATE) = 10
  AND C.CAR_TYPE = '세단'
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;

-- STRING, DATE
-- 164671
SELECT CONCAT("/home/grep/src/", F.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F
         JOIN (SELECT *
               FROM USED_GOODS_BOARD
               ORDER BY USED_GOODS_BOARD.VIEWS DESC
               LIMIT 1) UGB ON UGB.BOARD_ID = F.BOARD_ID
ORDER BY F.FILE_ID DESC;

-- 132204
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
         JOIN DOCTOR D
              ON D.DR_ID = A.MDDR_ID
         JOIN PATIENT P
              ON P.PT_NO = A.PT_NO
WHERE A.MCDP_CD = 'CS'
  AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
  AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD;

-- 151141
SELECT HIS.HISTORY_ID,
       (DATEDIFF(END_DATE, START_DATE) + 1) *
       TRUNCATE((CAR.DAILY_FEE * (1 - COALESCE(DISCOUNT_RATE, 0) / 100)), 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
         JOIN CAR_RENTAL_COMPANY_CAR CAR
              ON CAR.CAR_ID = HIS.CAR_ID
         LEFT JOIN (SELECT PLAN_ID,
                           CAR_TYPE,
                           CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS SIGNED) AS DURATION_TYPE,
                           CAST(REPLACE(DISCOUNT_RATE, '%', '') AS SIGNED)    AS DISCOUNT_RATE
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN) PLAN ON PLAN.DURATION_TYPE = (
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN 0
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN 7
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN 30
        ELSE 90
        END
    ) AND PLAN.CAR_TYPE = CAR.CAR_TYPE
WHERE CAR.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HIS.HISTORY_ID DESC;

-- 164670
SELECT USER_ID,
       NICKNAME,
       CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2)                     AS 전체주소,
       CONCAT(SUBSTR(TLNO, 1, 3), "-", SUBSTR(TLNO, 4, 4), "-", SUBSTR(TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER
WHERE USER_ID IN (SELECT WRITER_ID
                  FROM USED_GOODS_BOARD
                  GROUP BY WRITER_ID
                  HAVING COUNT(*) >= 3)
ORDER BY USER_ID DESC
;

-- 131113
SELECT ORDER_ID,
       PRODUCT_ID,
       DATE_FORMAT(OUT_DATE, '%Y-%m-%d'),
       CASE
           WHEN OUT_DATE IS NULL THEN '출고미정'
           WHEN DATEDIFF(OUT_DATE, '2022-05-01') <= 0 THEN '출고완료'
           ELSE '출고대기'
           END
FROM FOOD_ORDER
ORDER BY ORDER_ID ASC;

-- 151138
SELECT HISTORY_ID,
       CAR_ID,
       DATE_FORMAT(START_DATE, '%Y-%m-%d'),
       DATE_FORMAT(END_DATE, '%Y-%m-%d'),
       IF(DATEDIFF(HIS.END_DATE, HIS.START_DATE) + 1 >= 30, '장기 대여', '단기 대여')
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
WHERE YEAR(HIS.START_DATE) = 2022
  AND MONTH(HIS.START_DATE) = 9
ORDER BY HISTORY_ID DESC;

-- 157343
SELECT CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%네비게이션%'
ORDER BY CAR_ID DESC
;

-- 164672
SELECT BOARD_ID,
       WRITER_ID,
       TITLE,
       PRICE,
       CASE
           WHEN STATUS = 'SALE' THEN '판매중'
           WHEN STATUS = 'DONE' THEN '거래완료'
           ELSE '예약중'
           END AS STATUS
FROM USED_GOODS_BOARD
WHERE YEAR(CREATED_DATE) = 2022
  AND MONTH(CREATED_DATE) = 10
  AND DAY(CREATED_DATE) = 05
ORDER BY BOARD_ID DESC;

-- 59411
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_OUTS OUTS
         JOIN ANIMAL_INS INS
              ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
ORDER BY DATEDIFF(OUTS.DATETIME, INS.DATETIME) DESC
LIMIT 2;

-- 299308
SELECT CONCAT(TRUNCATE((MONTH(DIFFERENTIATION_DATE) - 1) / 3, 0) + 1, "Q") AS QUARTER,
       COUNT(*)                                                            AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY CONCAT(TRUNCATE((MONTH(DIFFERENTIATION_DATE) - 1) / 3, 0) + 1, "Q")
ORDER BY CONCAT(TRUNCATE((MONTH(DIFFERENTIATION_DATE) - 1) / 3, 0) + 1, "Q") ASC;

-- 131529
SELECT SUBSTR(PRODUCT_CODE, 1,2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE, 1,2)
ORDER BY SUBSTR(PRODUCT_CODE, 1,2) ASC;

-- 284530
SELECT YEAR(YM) AS YEAR, ROUND(AVG(PM_VAL1), 2) AS `PM10`, ROUND(AVG(PM_VAL2), 2) AS `PM2.5`
FROM AIR_POLLUTION
WHERE LOCATION2 = '수원'
GROUP BY YEAR(YM)
ORDER BY YEAR ASC;

-- 298516
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE YEAR(TIME) = 2021;
