-- 273709
select sum(price) as `TOTAL_PRICE`
from item_info
where rarity = 'LEGEND';

-- 131115
select *
from FOOD_PRODUCT
where PRICE = (select max(price) from FOOD_PRODUCT);

-- 298515
select concat(max(length), "cm")  as `MAX_LENGTH` from fish_info;

-- 131697
SELECT max(PRICE) as `MAX_PRICE` from PRODUCT;

-- 157339
SELECT
    car.CAR_ID,
    car.CAR_TYPE,
    TRUNCATE(
            car.DAILY_FEE * 30 * (100 - IFNULL(dp.DISCOUNT_RATE, 0)) / 100,
            0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS car
         LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS hist
                   ON hist.CAR_ID = car.CAR_ID
                       AND hist.START_DATE <= '2022-11-30'
                       AND hist.END_DATE >= '2022-11-01'
         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS dp
              ON dp.CAR_TYPE = car.CAR_TYPE
                  AND dp.DURATION_TYPE = '30일 이상'
WHERE hist.CAR_ID IS NULL
  AND car.CAR_TYPE IN ('세단','SUV')
  AND TRUNCATE(
              car.DAILY_FEE * 30 * (100 - IFNULL(dp.DISCOUNT_RATE,0)) / 100,
              0) <= 2000000
GROUP BY car.CAR_ID
ORDER BY FEE DESC, car.CAR_ID DESC;

-- 273711
SELECT DISTINCT
    child.ITEM_ID,
    child.ITEM_NAME,
    child.RARITY
FROM ITEM_TREE it
         JOIN ITEM_INFO parent
              ON parent.ITEM_ID = it.PARENT_ITEM_ID
                  AND parent.RARITY = 'RARE'
         JOIN ITEM_INFO child
              ON child.ITEM_ID = it.ITEM_ID
ORDER BY child.ITEM_ID DESC;

-- 299307
SELECT
    ID,
    CASE
        WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
        WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
        WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH'
        END
        AS `SIZE`
FROM ECOLI_DATA
ORDER BY ID;

-- 299305
SELECT p.ID,
       COUNT(c.ID) AS CHILD_COUNT
FROM ECOLI_DATA p
         LEFT JOIN ECOLI_DATA c
                   ON c.PARENT_ID = p.ID
GROUP BY p.ID
ORDER BY p.ID;

-- 301647
SELECT child.ID, child.GENOTYPE, parent.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA child
         JOIN ECOLI_DATA parent
              ON parent.ID = child.PARENT_ID
WHERE parent.GENOTYPE | child.GENOTYPE = child.GENOTYPE
ORDER BY child.ID;

-- 301649
SELECT
    ID,
    CASE
        WHEN RATE <= 0.25 THEN 'LOW'
        WHEN RATE <= 0.50 THEN 'MEDIUM'
        WHEN RATE <= 0.75 THEN 'HIGH'
        ELSE 'CRITICAL'
    END AS COLONY_NAME
FROM (
         SELECT ID,
                PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS RATE
         FROM ECOLI_DATA
     ) t
ORDER BY ID;

-- 361650
WITH RECURSIVE GEN(ID, PARENT_ID, LEVEL) AS (
    SELECT ID, PARENT_ID, 1 AS LEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT N.ID, N.PARENT_ID, GEN.LEVEL + 1
    FROM ECOLI_DATA N
             JOIN GEN ON N.PARENT_ID = GEN.ID
    WHERE LEVEL < 3
)
SELECT ID FROM GEN
WHERE LEVEL = 3
ORDER BY ID;

-- 131532
SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, UI.GENDER AS GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM ONLINE_SALE OS
         JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER;