-- programmers 157342
SELECT c.CAR_ID as CAR_ID, ROUND(AVG(DATEDIFF(c.END_DATE, c.START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY c
GROUP BY c.CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;